Update build-karbon.yaml

diff --git a/.github/workflows/build-karbon.yaml b/.github/workflows/build-karbon.yaml
--- a/.github/workflows/build-karbon.yaml
+++ b/.github/workflows/build-karbon.yaml
@@ -33,7 +33,7 @@ jobs:
         uses: actions/checkout@v3
 
       - name: Set up Python
-        uses: actions/setup-python@v4
+        uses: actions/setup-python@v5
         with:
           python-version: '3.11'
           cache: 'pip'
@@ -41,13 +41,14 @@ jobs:
       - name: Install virtualenv
         shell: bash
         run: |
-          python -m pip install --upgrade pip
-          python -m pip install virtualenv
+          python3 -m pip install --upgrade pip
+          python3 -m pip install virtualenv
 
       - name: Create and activate virtual environment
         shell: bash
         run: |
-          python -m virtualenv --clear venv
+          unset PYTHONPATH PYTHONHOME
+          python3 -m virtualenv --clear venv
           if [ "${{ matrix.os }}" = "windows-latest" ]; then
             source venv/Scripts/activate
             VENV_PYTHON="venv/Scripts/python"
@@ -69,7 +70,7 @@ jobs:
             VENV_PYTHON="venv/bin/python"
           fi
           "$VENV_PYTHON" -m pip install --upgrade pip setuptools wheel
-          "$VENV_PYTHON" -m pip install --no-cache-dir --force-reinstall pyinstaller==5.13.2 || { echo "Failed to install PyInstaller"; exit 1; }
+          "$VENV_PYTHON" -m pip install --no-cache-dir --force-reinstall pyinstaller==5.13.2 pyinstaller-hooks-contrib==2024.8 || { echo "Failed to install PyInstaller"; exit 1; }
           "$VENV_PYTHON" -m pip install -r requirements.txt || true
 
       - name: Debug PyInstaller installation
